### ISSUE TITLE
Compute Canada Readme

### ISSUE THREAD

**Issue by smh997** [fani-lab/Library#1]
> Thanks to @Hamedloghmani for creating a guide to help us deploy our projects on _ComputeCanada_.
Recently, @hosseinfani suggested having a Readme in this public repository to complete the previous guide in some way and publicize it to let anyone anywhere (in Canada) use it.

For now, it has these parts:
- [x] Create an Account 
- [x] Login
- [x] Connect to Servers
- [x] Deploy Project
- [x] Execute Project
- [x] Monitor Progress

**Comment by smh997** [comment]
_Create an Account_ and _Login_ tips are now available.
Other parts are going to be added, and at the end, I will create a pull request.

**Comment by hosseinfani** [comment]
@smh997 
I had a look at your fork. Very nice!

**Comment by smh997** [comment]
@hosseinfani 
Thank you very much for your gracious feedback. It will be finished by today.

**Comment by smh997** [comment]
All is done. However, I need to execute our project more on Compute Canada to add a meaningful experience about using GPU in the running.
By the way, it is almost ready for anyone to begin their journey in utilizing Compute Canada.

**Comment by smh997** [comment]
@hosseinfani 
All is done. However, I need to execute our project more on Compute Canada to add a meaningful experience about using GPU in the running.
By the way, it is almost ready for anyone to begin their journey in utilizing Compute Canada.

**Comment by smh997** [comment]
@hosseinfani 
I do not have access to make a `pull request` via Development:
![tempsnip](https://user-images.githubusercontent.com/38455739/227699573-ad8bffa2-4437-4e91-bf23-d51f364b10ca.png)

I can also open a pull request separately, and then we can link the issue to the pull request for clean work.

 I am just asking for any preference.

**Comment by hosseinfani** [comment]
@smh997 
thank you. yes, please create a pr from your fork. I'll merge it.

**Comment by smh997** [comment]
Thank you. I did it.

**Comment by smh997** [comment]
@hosseinfani 
Thank you. I did it.
